version: '3.8'

services:
  frontend:
    image: node:20-alpine
    volumes:
      - ./frontend:/app 
    ports:
      - 5173:5173
    working_dir: /app
    command: npm run setup

  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    command: npm run server
